### ISSUE TITLE
demo

### ISSUE THREAD

**Issue by di48l069** [ImFluffeh/SChat#1]
@ImFluffeh good day, where can I find a live demo?

**Comment by ImFluffeh** [comment]
I unfortunately haven't yet had the time to create one. However, if you do find that some things do not function as intended, do feel free to let me know.

**Comment by di48l069** [comment]
Okay thanks

**Comment by ImFluffeh** [comment]
Oh, and just a heads up, you will probably have to work out the kinks with the CSRF if you are not using AJAX/an application to send form login data.
